/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PCI_SNIFF_H_RPCGEN
#define _PCI_SNIFF_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PCISNIFF 0x3012225
#define PCISNIFF_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define START 1
extern  int * start_1(void *, CLIENT *);
extern  int * start_1_svc(void *, struct svc_req *);
#define PAUSE 2
extern  int * pause_1(void *, CLIENT *);
extern  int * pause_1_svc(void *, struct svc_req *);
#define INTERVAL 3
extern  int * interval_1(int *, CLIENT *);
extern  int * interval_1_svc(int *, struct svc_req *);
#define STOP 4
extern  int * stop_1(void *, CLIENT *);
extern  int * stop_1_svc(void *, struct svc_req *);
extern int pcisniff_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
static void pcisniff_1 (struct svc_req *, SVCXPRT *);

#else /* K&R C */
#define START 1
extern  int * start_1();
extern  int * start_1_svc();
#define PAUSE 2
extern  int * pause_1();
extern  int * pause_1_svc();
#define INTERVAL 3
extern  int * interval_1();
extern  int * interval_1_svc();
#define STOP 4
extern  int * stop_1();
extern  int * stop_1_svc();
extern int pcisniff_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PCI_SNIFF_H_RPCGEN */
