/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PCI_SNIFF_H_RPCGEN
#define _PCI_SNIFF_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PCISNIFF 0x3012225
#define PCISNIFF_V2 3

#if defined(__STDC__) || defined(__cplusplus)
#define START 1
extern  int * start_3(void *, CLIENT *);
extern  int * start_3_svc(void *, struct svc_req *);
#define PAUSE 2
extern  int * pause_3(void *, CLIENT *);
extern  int * pause_3_svc(void *, struct svc_req *);
#define INTERVAL 3
extern  int * interval_3(int *, CLIENT *);
extern  int * interval_3_svc(int *, struct svc_req *);
#define STOP 4
extern  int * stop_3(void *, CLIENT *);
extern  int * stop_3_svc(void *, struct svc_req *);
extern int pcisniff_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define START 1
extern  int * start_3();
extern  int * start_3_svc();
#define PAUSE 2
extern  int * pause_3();
extern  int * pause_3_svc();
#define INTERVAL 3
extern  int * interval_3();
extern  int * interval_3_svc();
#define STOP 4
extern  int * stop_3();
extern  int * stop_3_svc();
extern int pcisniff_3_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PCI_SNIFF_H_RPCGEN */
